name: Pulumi
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: docker://pulumi/actions
        with:
          args: preview
        env:
          ARM_CLIENT_ID: ${{ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{ARM_CLIENT_SECRET}}
          ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: pr
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_ON_PR: 1